name: CI Defense des Tours 🚀

on: [push, pull_request]

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-LaDefenseDesTours-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-LaDefenseDesTours-
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.CI_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.CI_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
          targetPlatform: ${{ matrix.targetPlatform }}

  build:
    name: Build 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-LaDefenseDesTours-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-LaDefenseDesTours-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.CI_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.CI_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
