name: CI Validation - Defense des Tours 🚀

on: [push, pull_request]

jobs:
  test:
    name: Automated Tests 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-LaDefenseDesTours
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.CI_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.CI_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
